"""
tests/integration/test_urls.py

Integration tests for URL creation, custom aliases, validation, and metadata retrieval.
"""

from __future__ import annotations

from datetime import UTC, datetime, timedelta

import pytest


@pytest.mark.anyio
async def test_shorten_url_anonymous(client):
    """Test shortening a URL anonymously with autogenerated Base62 short code."""
    payload = {
        "url": "https://example.com/very/long/path?param=123",
    }
    response = await client.post("/api/v1/urls", json=payload)
    assert response.status_code == 201

    body = response.json()
    assert body["success"] is True
    data = body["data"]
    assert data["original_url"] == "https://example.com/very/long/path?param=123"
    assert len(data["short_code"]) == 7
    assert data["short_url"].endswith(f"/{data['short_code']}")
    assert data["is_custom"] is False
    assert data["click_count"] == 0


@pytest.mark.anyio
async def test_shorten_url_with_custom_alias(client):
    """Test creating a short URL with a specific custom alias."""
    payload = {
        "url": "https://fastapi.tiangolo.com",
        "custom_alias": "fastapi-docs",
    }
    response = await client.post("/api/v1/urls", json=payload)
    assert response.status_code == 201

    body = response.json()
    assert body["data"]["short_code"] == "fastapi-docs"
    assert body["data"]["is_custom"] is True


@pytest.mark.anyio
async def test_shorten_url_duplicate_custom_alias(client):
    """Test that attempting to reuse an existing alias returns a 400/409 error."""
    payload = {
        "url": "https://first-example.com",
        "custom_alias": "unique-alias-1",
    }
    res1 = await client.post("/api/v1/urls", json=payload)
    assert res1.status_code == 201

    payload_dup = {
        "url": "https://second-example.com",
        "custom_alias": "unique-alias-1",
    }
    res2 = await client.post("/api/v1/urls", json=payload_dup)
    assert res2.status_code == 400  # AliasAlreadyExistsError -> 400


@pytest.mark.anyio
async def test_shorten_url_reserved_alias(client):
    """Test that reserved words cannot be used as custom aliases."""
    payload = {
        "url": "https://example.com",
        "custom_alias": "health",
    }
    response = await client.post("/api/v1/urls", json=payload)
    assert response.status_code == 400


@pytest.mark.anyio
async def test_shorten_url_with_future_expiry(client):
    """Test creating a short URL with future expiry date."""
    future_time = (datetime.now(UTC) + timedelta(days=7)).isoformat()
    payload = {
        "url": "https://example.com/expiring",
        "expiry": future_time,
    }
    response = await client.post("/api/v1/urls", json=payload)
    assert response.status_code == 201
    assert response.json()["data"]["expires_at"] is not None


@pytest.mark.anyio
async def test_shorten_url_with_past_expiry_fails(client):
    """Test that setting past expiry date is rejected by validation."""
    past_time = (datetime.now(UTC) - timedelta(days=1)).isoformat()
    payload = {
        "url": "https://example.com/invalid-expiry",
        "expiry": past_time,
    }
    response = await client.post("/api/v1/urls", json=payload)
    assert response.status_code == 422


@pytest.mark.anyio
async def test_get_url_detail(client):
    """Test retrieving details of an existing shortened URL."""
    create_res = await client.post(
        "/api/v1/urls",
        json={"url": "https://news.ycombinator.com", "custom_alias": "hn-news"},
    )
    assert create_res.status_code == 201

    get_res = await client.get("/api/v1/urls/hn-news")
    assert get_res.status_code == 200
    assert get_res.json()["data"]["original_url"].rstrip("/") == "https://news.ycombinator.com"


@pytest.mark.anyio
async def test_get_nonexistent_url_detail(client):
    """Test retrieving details of a non-existent short code returns 404."""
    response = await client.get("/api/v1/urls/non-existent-code")
    assert response.status_code == 404
