"""
tests/unit/test_url_service.py

Unit tests for URLService business logic, Base62 code generation,
collision handling, custom alias conflict, and validation.
"""

from __future__ import annotations

import uuid
from datetime import UTC, datetime, timedelta
from unittest.mock import AsyncMock, MagicMock

import pytest

from app.core.exceptions import (
    AliasAlreadyExistsError,
    InvalidURLError,
    ShortURLNotFoundError,
    URLExpiredError,
)
from app.models.url import URL
from app.schemas.url import URLCreateRequest
from app.services.url_service import URLService


@pytest.fixture
def mock_cache():
    cache = MagicMock()
    cache.get_original_url = AsyncMock(return_value=None)
    cache.set_original_url = AsyncMock(return_value=None)
    cache.evict_short_code = AsyncMock(return_value=None)
    return cache


@pytest.fixture
def mock_db():
    return AsyncMock()


@pytest.mark.anyio
async def test_create_short_url_autogenerated(mock_db, mock_cache):
    svc = URLService(db=mock_db, cache=mock_cache)
    svc.repo.short_code_exists = AsyncMock(return_value=False)

    fake_id = uuid.uuid4()
    now = datetime.now(UTC)
    mock_url_record = URL(
        id=fake_id,
        original_url="https://github.com/fastapi/fastapi",
        short_code="aB3dE12",
        user_id=None,
        is_active=True,
        is_custom=False,
        click_count=0,
        expires_at=None,
        created_at=now,
        updated_at=now,
    )
    svc.repo.create = AsyncMock(return_value=mock_url_record)

    payload = URLCreateRequest(url="https://github.com/fastapi/fastapi")
    response = await svc.create_short_url(payload)

    assert response.original_url == "https://github.com/fastapi/fastapi"
    assert response.short_code == "aB3dE12"
    assert response.is_custom is False
    mock_cache.set_original_url.assert_called_once()


@pytest.mark.anyio
async def test_create_short_url_custom_alias(mock_db, mock_cache):
    svc = URLService(db=mock_db, cache=mock_cache)
    svc.repo.short_code_exists = AsyncMock(return_value=False)

    fake_id = uuid.uuid4()
    now = datetime.now(UTC)
    mock_url_record = URL(
        id=fake_id,
        original_url="https://docs.python.org",
        short_code="py-docs",
        user_id=None,
        is_active=True,
        is_custom=True,
        click_count=0,
        expires_at=None,
        created_at=now,
        updated_at=now,
    )
    svc.repo.create = AsyncMock(return_value=mock_url_record)

    payload = URLCreateRequest(url="https://docs.python.org", custom_alias="py-docs")
    response = await svc.create_short_url(payload)

    assert response.short_code == "py-docs"
    assert response.is_custom is True


@pytest.mark.anyio
async def test_create_short_url_duplicate_alias_raises(mock_db, mock_cache):
    svc = URLService(db=mock_db, cache=mock_cache)
    svc.repo.short_code_exists = AsyncMock(return_value=True)

    payload = URLCreateRequest(url="https://example.com", custom_alias="taken-alias")
    with pytest.raises(AliasAlreadyExistsError):
        await svc.create_short_url(payload)


@pytest.mark.anyio
async def test_create_short_url_reserved_alias_raises(mock_db, mock_cache):
    svc = URLService(db=mock_db, cache=mock_cache)

    payload = URLCreateRequest(url="https://example.com", custom_alias="health")
    with pytest.raises(InvalidURLError):
        await svc.create_short_url(payload)


@pytest.mark.anyio
async def test_resolve_short_code_from_cache(mock_db, mock_cache):
    svc = URLService(db=mock_db, cache=mock_cache)
    mock_cache.get_original_url = AsyncMock(return_value="https://cached.org")

    resolved = await svc.resolve_short_code("cached123")
    assert resolved == "https://cached.org"


@pytest.mark.anyio
async def test_resolve_short_code_expired_raises(mock_db, mock_cache):
    svc = URLService(db=mock_db, cache=mock_cache)
    mock_cache.get_original_url = AsyncMock(return_value=None)

    expired_time = datetime.now(UTC) - timedelta(days=1)
    record = URL(
        id=uuid.uuid4(),
        original_url="https://expired.org",
        short_code="exp1234",
        is_active=True,
        expires_at=expired_time,
    )
    svc.repo.get_by_short_code = AsyncMock(return_value=record)

    with pytest.raises(URLExpiredError):
        await svc.resolve_short_code("exp1234")


@pytest.mark.anyio
async def test_resolve_short_code_not_found_raises(mock_db, mock_cache):
    svc = URLService(db=mock_db, cache=mock_cache)
    mock_cache.get_original_url = AsyncMock(return_value=None)
    svc.repo.get_by_short_code = AsyncMock(return_value=None)

    with pytest.raises(ShortURLNotFoundError):
        await svc.resolve_short_code("missing")
